CLIP_LABELS = {
    # People and Portraits
    "portrait_professional": "a professional headshot portrait of a person",
    "portrait_casual": "a casual portrait of a person smiling",
    "selfie": "a selfie photograph taken by someone",
    "group_photo": "a group photo of people together",
    "wedding_photo": "a photograph from a wedding ceremony",
    "graduation_photo": "a graduation ceremony photograph",
    "baby_photo": "a photograph of a baby or infant",
    "child_portrait": "a portrait of a young child",
    "elderly_portrait": "a portrait of an elderly person",
    "family_photo": "a family photograph with multiple generations",
    "business_meeting": "a photograph of people in a business meeting",
    "school_portrait": "a school portrait of a student in uniform",
    "formal_wear": "a portrait of a person dressed in formal attire",
    "casual_wear": "a portrait of a person dressed in casual attire",
    "sports_team": "a group photo of a sports team in uniform",
    "artist_portrait": "a portrait of a creative artist",
    "musician_portrait": "a portrait of a musician with their instrument",
    "actor_headshot": "a professional headshot of an actor",
    "outdoor_portrait": "a portrait of a person outdoors",
    "indoor_portrait": "a portrait of a person indoors",
    "vintage_portrait": "a black and white or sepia-toned portrait",
    "military_portrait": "a portrait of a person in military uniform",
    "celebrity_photo": "a photograph of a famous person",
    "politician_portrait": "a portrait of a politician",
    "sibling_photo": "a photo of siblings together",
    "parent_child": "a photograph showing a parent with their child",
    "couple_photo": "a photograph of a couple together",
    "engagement_photo": "a photograph from an engagement session",
    "baby_shower": "a photo from a baby shower event",
    "maternity_photo": "a maternity portrait of an expecting mother",
    "candid_photo": "a candid photograph capturing a moment",
    "sports_action": "a photograph of a person playing a sport",
    "student_graduation": "a portrait of a student on graduation day",
    "travel_photo": "a photograph of a person while traveling",
    "cultural_portrait": "a portrait of a person in traditional attire",
    "beach_portrait": "a portrait of a person at the beach",
    "mountain_portrait": "a portrait of a person in a mountainous area",
    "night_portrait": "a portrait taken at night",
    "street_portrait": "a candid portrait of a person in a street setting",
    "laughing_portrait": "a portrait of a person laughing",
    "smiling_portrait": "a portrait of a person smiling warmly",
    "serious_portrait": "a portrait of a person with a serious expression",
    "model_portrait": "a professional portrait of a fashion model",
    "science_lab": "a photo of a person working in a lab",
    "chef_portrait": "a portrait of a chef in a kitchen",
    "teacher_classroom": "a photo of a teacher in a classroom",
    "doctor_portrait": "a portrait of a doctor in medical attire",
    "farmer_portrait": "a portrait of a farmer outdoors",
    "engineer_worksite": "a photo of an engineer at a construction site",
    "firefighter_portrait": "a portrait of a firefighter in uniform",
    "police_officer": "a portrait of a police officer in uniform",
    "pilot_portrait": "a portrait of an airline pilot",
    "happy_family": "a photo of a happy family together",
    "sad_portrait": "a portrait of a person with a sad expression",
    "confused_portrait": "a portrait of a person looking confused",
    "thinking_pose": "a portrait of a person in a thoughtful pose",
    "celebration_photo": "a photo of people celebrating an occasion",
    "farewell_party": "a photo from a farewell party",
    "birthday_party": "a photograph from a birthday celebration",
    "anniversary_photo": "a photo from a wedding anniversary celebration",
    "class_reunion": "a photo of a school or college reunion",
    "relaxing_pose": "a portrait of a person in a relaxed pose",
    "reading_portrait": "a portrait of a person reading a book",
    "walking_portrait": "a portrait of a person walking outdoors",
    "fitness_portrait": "a portrait of a person doing fitness activities",
    "yoga_pose": "a photograph of a person in a yoga pose",
    "gym_portrait": "a portrait of a person working out at the gym",
    "musician_in_concert": "a photo of a musician performing live",
    "surprised_portrait": "a portrait of a person looking surprised",
    "sleeping_portrait": "a portrait of a person sleeping",
    "ballet_dancer": "a portrait of a ballet dancer in costume",
    "graduation_cap_gown": "a portrait of a graduate in cap and gown",
    "classroom_photo": "a photograph of students in a classroom",
    "scientist_portrait": "a portrait of a scientist",
    "volunteer_event": "a photograph of people volunteering",
    "dancer_portrait": "a portrait of a dancer in a dance pose",
    "artist_at_work": "a photo of an artist working on their art",
    "couple_kissing": "a photograph of a couple sharing a kiss",
    "friends_hugging": "a photograph of friends hugging",
    "camping_portrait": "a portrait of a person camping outdoors",
    "festival_photo": "a photograph from a cultural or music festival",
    "graduation_party": "a photo from a graduation party celebration",
    "airport_photo": "a photo of a person at an airport",
    "child_playing": "a photograph of a child playing",
    "outdoor_activity": "a photo of people engaged in outdoor activities",
    "city_life": "a photo of a person in an urban city setting",
    "rural_life": "a photo of a person in a rural setting",
    "digital_nomad": "a photo of a person working on a laptop outdoors",
    "photographer_action": "a photo of a photographer taking a photo",
    "high_school_prom": "a portrait of a high school student at prom",
    "fashion_show": "a photo of a model on the runway at a fashion show",
    "horse_rider": "a portrait of a person riding a horse",
    
    # Nature and Landscapes
    "mountain_landscape": "a majestic mountain landscape",
    "beach_scene": "a scenic beach with ocean waves",
    "forest_scene": "a dense forest with tall trees",
    "desert_landscape": "an arid desert landscape with sand dunes",
    "waterfall": "a flowing waterfall in nature",
    "sunset_scene": "a beautiful sunset over the horizon",
    "sunrise_scene": "a sunrise breaking over the horizon",
    "river_landscape": "a river flowing through the landscape",
    "lake_scene": "a peaceful lake surrounded by nature",
    "valley_landscape": "a vast valley between mountains",
    "hilltop_view": "a panoramic view from a hilltop",
    "glacier_scene": "a stunning glacier in a remote area",
    "tundra_landscape": "a vast tundra with low vegetation",
    "canyon_scene": "a deep canyon with rugged cliffs",
    "island_view": "a tropical island with lush vegetation",
    "prairie_landscape": "a wide-open prairie with tall grasses",
    "swamp_scene": "a mysterious swamp with fog and cypress trees",
    "field_of_flowers": "a vibrant field filled with colorful flowers",
    "coastal_cliff": "a dramatic cliff overlooking the ocean",
    "rainforest_scene": "a dense rainforest teeming with wildlife",
    "arctic_landscape": "a stark arctic landscape with ice and snow",
    "savanna_scene": "an expansive savanna with scattered acacia trees",
    "rocky_coastline": "a rugged coastline with crashing waves",
    "meadow_scene": "a serene meadow with wildflowers and butterflies",
    "volcano_view": "a towering volcano with smoke and ash",
    "countryside": "a picturesque countryside with rolling hills",
    "frozen_lake": "a tranquil frozen lake in winter",
    "hot_springs": "natural hot springs surrounded by mountains",
    "desert_flower": "wildflowers blooming in the desert",
    "night_sky": "a starry night sky over a peaceful landscape",
    "foggy_morning": "a misty morning in a tranquil valley",
    "cave_scene": "an underground cave with stalactites and stalagmites",
    "stone_hedge": "a mystical stone formation in nature",
    "wildlife_refuge": "a sanctuary for wildlife in a natural setting",
    "harbor_scene": "a calm harbor with boats and reflections",
    "cactus_field": "a field of cacti in a desert landscape",
    "serene_pond": "a quiet pond surrounded by trees",
    "autumn_foliage": "colorful autumn leaves in a forest",
    "tropical_forest": "a lush tropical forest with exotic plants",
    "highland_scene": "a scenic highland with rolling hills",
    "cherry_blossom": "cherry blossom trees in full bloom",
    "mossy_rocks": "moss-covered rocks near a stream",
    "ocean_view": "a stunning view of the ocean from a cliff",
    "ancient_trees": "old trees in a serene forest",
    "mountain_lake": "a pristine lake nestled in the mountains",
    "glowing_caverns": "caverns illuminated by natural light",
    "snowy_peak": "a snow-capped mountain peak",
    "wooded_path": "a tranquil path through a wooded area",
    "pasture_scene": "a green pasture with grazing animals",
    "tropical_beach": "a serene tropical beach with palm trees",
    "scenic_overlook": "a viewpoint with a panoramic landscape",
    "cloudy_sky": "dramatic clouds above a peaceful scene",
    "river_delta": "a river delta with winding waterways",
    "iceberg": "a massive iceberg floating in the ocean",
    "rainbow_after_rain": "a beautiful rainbow after a rainstorm",
    "meandering_stream": "a gentle stream meandering through a valley",
    "mountain_reflection": "mountains reflecting in a calm lake",
    "climbing_mountains": "a challenging mountain climbing scene",
    "wildflower_meadow": "a meadow bursting with wildflowers",
    "secluded_bay": "a hidden bay with clear waters",
    "tall_grasses": "tall grasses swaying in the breeze",
    "cliffside_path": "a narrow path along a cliffside",
    "ancient_ruins": "ancient ruins in a natural setting",
    "rocky_hill": "a rocky hill with sparse vegetation",
    "sunlit_forest": "a sunlit forest with dappled light",
    "colorful_reef": "a vibrant coral reef underwater",
    "mountain_sunset": "a sunset behind majestic mountains",
    "serene_fjord": "a calm fjord with steep cliffs",
    "whimsical_grove": "a whimsical grove of trees",
    "misty_lake": "a mist-covered lake at dawn",
    "tall_redwoods": "towering redwoods in a forest",
    "lush_garden": "a flourishing garden with diverse plants",
    "sunflower_field": "a field of sunflowers facing the sun",
    "golden_woods": "golden leaves in a tranquil woodland",
    "tropical_waterfall": "a waterfall in a tropical paradise",
    "fishing_village": "a quaint fishing village by the sea",
    "rainy_day": "a peaceful rainy day in a rural setting",
    "mountain_stream": "a clear stream flowing through the mountains",
    "starry_night": "a tranquil scene under a starry sky",
    "seaside_cliffs": "cliffs overlooking the crashing waves",
    "bamboo_forest": "a serene bamboo forest swaying in the wind",
    "winding_road": "a picturesque winding road through the countryside",
    "morning_dew": "dewdrops on grass in the early morning light",
    "hiking_trail": "a rugged hiking trail through the mountains",
    "cloudy_mountain": "a mountain peak shrouded in clouds",
    "misty_mountains": "mountains enveloped in morning mist",
    "sunset_reflection": "the reflection of a sunset on water",
    "vibrant_foliage": "vibrant leaves in autumn colors",
    "ancient_forest": "a forest with ancient, towering trees",
    "hidden_waterfall": "a secluded waterfall surrounded by greenery",
    "crystal_clear_lake": "a lake with crystal clear waters",
    "blooming_cactus": "a cactus in bloom against a desert backdrop",
    "open_sea": "the vastness of the open sea under a clear sky",
    "desert_horizon": "the horizon of a vast desert landscape",

    # Urban and Architecture
    "skyscraper": "a tall skyscraper in a city",
    "city_street": "a busy city street with buildings",
    "historic_building": "a historic or classical building",
    "modern_architecture": "modern architectural design building",
    "bridge": "a bridge spanning water or terrain",
    "residential_building": "a residential apartment building",
    "shopping_mall": "a modern shopping mall interior",
    "train_station": "a train station with platforms",
    "airport_terminal": "an airport terminal building",
    "urban_park": "an urban park in a city setting",
    "town_square": "a lively town square with people and cafes",
    "library": "a contemporary or historic library building",
    "museum": "a museum showcasing art or history",
    "waterfront": "a waterfront area with views of water",
    "stadium": "a large sports stadium with seating",
    "office_building": "a corporate office building in a business district",
    "parking_garage": "a multi-story parking garage structure",
    "highway": "a busy highway with vehicles and overpasses",
    "cultural_center": "a cultural center for community events",
    "industrial_area": "an industrial area with factories",
    "suburban_neighborhood": "a quiet suburban neighborhood with homes",
    "condominium": "a modern condominium complex",
    "townhouse": "a row of townhouses in an urban setting",
    "city_hall": "a city hall building with government offices",
    "fountain": "a decorative fountain in a public plaza",
    "cathedral": "a grand cathedral or church building",
    "theater": "an ornate theater for performances",
    "gymnasium": "a gymnasium or fitness center",
    "community_center": "a community center with various facilities",
    "bike_path": "a bike path running through an urban area",
    "zoo": "a city zoo with various animal enclosures",
    "historic_district": "a historic district with preserved architecture",
    "public_art": "a public art installation in a city",
    "plaza": "a public plaza surrounded by buildings",
    "skatepark": "an outdoor skatepark with ramps and rails",
    "bridle_path": "a bridle path for horseback riding in a park",
    "seafront": "a vibrant seafront promenade",
    "marketplace": "an open-air marketplace with vendors",
    "community_garden": "a community garden in an urban neighborhood",
    "green_roof": "a building with a green or living roof",
    "co-working_space": "a modern co-working space for professionals",
    "town_museum": "a local town museum showcasing history",
    "convention_center": "a large convention center for events",
    "art_gallery": "an art gallery exhibiting contemporary art",
    "row_houses": "a row of colorful row houses",
    "observatory": "an observatory for stargazing in a city",
    "clock_tower": "a clock tower as a city landmark",
    "art_installation": "a temporary art installation in a public space",
    "water_treatment_plant": "a water treatment facility in an industrial area",
    "railway_crossing": "a railway crossing with signals and gates",
    "amphitheater": "an outdoor amphitheater for performances",
    "mansion": "an opulent mansion in a historic district",
    "bicycle_rack": "a bicycle rack in an urban area",
    "playground": "a children's playground in a park",
    "pavilion": "a pavilion in a public garden or park",
    "sculpture_park": "a park featuring outdoor sculptures",
    "community_college": "a community college campus",
    "science_center": "a science center with interactive exhibits",
    "fire_station": "a local fire station building",
    "police_station": "a municipal police station",
    "ferry_terminal": "a ferry terminal for boats and passengers",
    "fish_market": "a bustling fish market by the waterfront",
    "solar_farm": "a solar farm with panels in a city outskirts",
    "wind_turbine": "a wind turbine in an urban landscape",
    "roadside_stand": "a roadside stand selling local produce",
    "bike_share_station": "a bike share station in the city",
    "flea_market": "a flea market with vendors and shoppers",
    "cafe": "a cozy cafe with outdoor seating",
    "chalet": "a wooden chalet in a mountainous area",
    "gas_station": "a gas station with convenience store",
    "bus_terminal": "a bus terminal with multiple stops",
    "courthouse": "a municipal courthouse for legal proceedings",
    "town_post_office": "a post office serving a town or city",
    "open_air_concert_venue": "an open-air venue for concerts",
    "art_deco_building": "a historic art deco building",
    "historic_mansion": "a preserved historic mansion",
    "science_laboratory": "a modern science laboratory building",
    "storage_facility": "a storage facility for personal items",
    "youth_center": "a youth center with activities and programs",
    "sports_complex": "a sports complex with various facilities",
    "botanical_garden": "a botanical garden featuring diverse plant life",
    "monument": "a monument commemorating an event or person",
    "town_clock": "a decorative town clock in a public space",
    "historic_bridge": "a historic bridge known for its architecture",
    "urban_farm": "an urban farm integrated within a city",
    "civic_center": "a civic center for community events and government",
    "recreation_center": "a recreation center with sports facilities",
    "ballet_theater": "a theater specifically for ballet performances",
    "industrial_warehouse": "a large warehouse used for storage and distribution",
    "chamber_of_commerce": "a building housing the chamber of commerce",
    "beach_boardwalk": "a boardwalk along a beach for walking and dining",
    "skyscraper_lobby": "a luxurious lobby in a skyscraper",
    "cultural_institute": "a cultural institute promoting local art and history",
    "pet_store": "a pet store in a suburban shopping area",
    "laundromat": "a self-service laundromat for residents",
    "hair_salon": "a hair salon in a busy shopping district",
    "yoga_studio": "a tranquil yoga studio in an urban area",
    "community_theater": "a community theater for local performances",
    "art_supply_store": "an art supply store for artists and hobbyists",
    "historic_mill": "a historic mill converted for modern use",
    "craft_market": "a craft market showcasing local artisans",
    "green_space": "an open green space in an urban setting",
    "eco_village": "an eco-village promoting sustainable living",
    "town_circle": "a circular gathering space in a town center",
    "public_restroom": "a public restroom facility in a park",
    "dog_park": "a designated dog park for pet owners",
    "performance_art_space": "a space dedicated to performance art events",

    # Animals and Wildlife
    "domestic_cat": "a photograph of a house cat",
    "domestic_dog": "a photograph of a pet dog",
    "wild_lion": "a lion in its natural habitat",
    "elephant": "an elephant in the wild",
    "bird_flying": "a bird flying in the sky",
    "bird_perched": "a bird perched on a branch",
    "fish_underwater": "a fish swimming underwater",
    "butterfly": "a butterfly on a flower",
    "spider": "a spider in its web",
    "horse": "a horse in a field",
    "tiger": "a tiger in the jungle",
    "giraffe": "a giraffe eating from a tall tree",
    "zebra": "a zebra grazing on the savannah",
    "kangaroo": "a kangaroo hopping in the outback",
    "penguin": "a penguin waddling on ice",
    "dolphin": "a dolphin jumping out of the ocean",
    "rabbit": "a rabbit in a garden",
    "squirrel": "a squirrel climbing a tree",
    "deer": "a deer in a forest",
    "bear": "a bear fishing in a river",
    "wolf": "a wolf howling at the moon",
    "fox": "a fox in a field",
    "owl": "an owl perched in a tree at night",
    "bat": "a bat flying at dusk",
    "crocodile": "a crocodile basking in the sun",
    "snake": "a snake slithering through grass",
    "frog": "a frog sitting on a lily pad",
    "seal": "a seal lounging on a rock",
    "octopus": "an octopus hiding in a coral reef",
    "antelope": "an antelope running across the plains",
    "peacock": "a peacock displaying its feathers",
    "moose": "a moose walking near a lake",
    "raccoon": "a raccoon rummaging through a trash can",
    "hedgehog": "a hedgehog curled up in a ball",
    "flamingo": "a flamingo standing in shallow water",
    "chameleon": "a chameleon on a branch",
    "quokka": "a quokka smiling at the camera",
    "narwhal": "a narwhal swimming in icy waters",
    "panda": "a panda eating bamboo",
    "koala": "a koala sleeping in a tree",
    "sloth": "a sloth hanging upside down in a tree",
    "armadillo": "an armadillo crossing a dirt road",
    "ibex": "an ibex climbing a rocky cliff",
    "tapir": "a tapir wading through a river",
    "manatee": "a manatee grazing on underwater plants",
    "bison": "a bison roaming on the plains",
    "ostrich": "an ostrich running in the desert",
    "gibbon": "a gibbon swinging through the trees",
    "starfish": "a starfish on the ocean floor",
    "jellyfish": "a jellyfish floating in the sea",
    "pufferfish": "a pufferfish swimming among coral",
    "lobster": "a lobster hiding in a rocky crevice",
    "sea_turtle": "a sea turtle gliding through the water",
    "goldfish": "a goldfish swimming in a bowl",
    "canary": "a canary singing in a cage",
    "parrot": "a parrot perched on a branch",
    "tarantula": "a tarantula on a rock",
    "peccary": "a peccary foraging in the underbrush",
    "dingo": "a dingo running along the beach",
    "okapi": "an okapi standing in the rainforest",
    "porcupine": "a porcupine climbing a tree",
    "elk": "an elk grazing in a meadow",
    "lynx": "a lynx prowling in the snow",
    "golden_eagle": "a golden eagle soaring in the sky",
    "manta_ray": "a manta ray swimming in the ocean",
    "stingray": "a stingray gliding over the seabed",
    "tortoise": "a tortoise moving slowly on land",
    "bunny": "a cute bunny in a garden",
    "carp": "a carp swimming in a pond",
    "vulture": "a vulture perched on a rock",
    "coyote": "a coyote howling in the desert",
    "kookaburra": "a kookaburra laughing on a branch",
    "anteater": "an anteater searching for ants",
    "meerkat": "a meerkat standing guard",
    "jaguar": "a jaguar resting in the sun",
    "capybara": "a capybara relaxing by a river",
    "red_panda": "a red panda climbing a tree",
    "wombat": "a wombat digging in the ground",
    "maned_wolf": "a maned wolf walking through grasslands",
    "cheetah": "a cheetah sprinting across the savannah",
    "binturong": "a binturong hanging from a branch",
    "fossa": "a fossa prowling in the forest",
    "arapaima": "an arapaima swimming in the Amazon River",
    "piranha": "a piranha in the water with sharp teeth",
    "salamander": "a salamander resting on a rock",
    "newt": "a newt swimming in a pond",
    "impala": "an impala jumping gracefully in the savannah",
    "bongo": "a bongo in the thick underbrush",
    "platypus": "a platypus swimming in a river",
    "axolotl": "an axolotl in a freshwater habitat",
    "marmoset": "a marmoset hanging from a tree branch",
    "tamarins": "tamarins playing in the canopy",
    "golden_frog": "a golden frog on a leaf",
    "toad": "a toad sitting on the ground",
    "serval": "a serval stalking its prey in the grasslands",
    "flying_squirrel": "a flying squirrel gliding between trees",
    "sifaka": "a sifaka jumping between branches",

    # Food and Cuisine (100)
        "restaurant_dish": "a professionally plated restaurant dish",
    "homemade_meal": "a homemade meal on a plate",
    "dessert": "a decorated dessert or pastry",
    "fresh_fruit": "fresh fruits arranged on a surface",
    "vegetables": "fresh vegetables arranged together",
    "sushi": "sushi rolls and sashimi",
    "pizza": "a pizza with toppings",
    "sandwich": "a prepared sandwich",
    "soup": "a bowl of hot soup",
    "beverage": "a beverage in a glass",
    "pasta": "a plate of pasta with sauce",
    "salad": "a colorful salad in a bowl",
    "grilled_meat": "grilled meat on a plate",
    "seafood": "a seafood platter with shrimp and oysters",
    "cheese_board": "a cheese board with assorted cheeses",
    "tacos": "a plate of tacos with various fillings",
    "ice_cream": "a scoop of ice cream in a bowl",
    "curry": "a bowl of curry with rice",
    "quiche": "a slice of quiche on a plate",
    "omelette": "a fluffy omelette with vegetables",
    "bread": "freshly baked bread on a cutting board",
    "sushi_bowl": "a sushi bowl with rice and toppings",
    "wrap": "a wrap filled with vegetables and protein",
    "muffins": "freshly baked muffins on a tray",
    "cake": "a decorated layer cake",
    "brownies": "chocolate brownies cut into squares",
    "pancakes": "a stack of pancakes with syrup",
    "waffles": "crispy waffles with toppings",
    "fruit_salad": "a colorful fruit salad in a bowl",
    "popcorn": "a bowl of freshly popped popcorn",
    "cookies": "a plate of assorted cookies",
    "donuts": "a box of assorted donuts",
    "tiramisu": "a slice of tiramisu on a plate",
    "chocolate": "a bar of chocolate broken into pieces",
    "sorbet": "a bowl of fruit sorbet",
    "biryani": "a plate of biryani with spices",
    "dim_sum": "a platter of dim sum dumplings",
    "pho": "a bowl of pho with herbs and meat",
    "pita": "pita bread with hummus",
    "fajitas": "a sizzling plate of fajitas",
    "ramen": "a bowl of ramen with toppings",
    "chili": "a bowl of chili with beans",
    "gratin": "a dish of potato gratin",
    "risotto": "a creamy risotto in a bowl",
    "smoothie": "a smoothie in a glass with a straw",
    "scones": "fresh scones with jam and cream",
    "pesto": "a bowl of pesto sauce with pasta",
    "tart": "a fruit tart on a plate",
    "cheesecake": "a slice of cheesecake with a crust",
    "potatoes": "mashed potatoes in a bowl",
    "vegetable_stir_fry": "a vegetable stir fry in a pan",
    "baked_goods": "assorted baked goods on a table",
    "cereal": "a bowl of cereal with milk",
    "nachos": "a plate of nachos with cheese and toppings",
    "fish_fry": "crispy fried fish on a plate",
    "kebab": "skewered kebabs on a grill",
    "cocoa": "a mug of hot cocoa",
    "jambalaya": "a bowl of jambalaya with sausage",
    "miso_soup": "a bowl of miso soup with tofu",
    "lasagna": "a slice of lasagna on a plate",
    "egg_salad": "egg salad served in a bowl",
    "fruit_juice": "a glass of freshly squeezed fruit juice",
    "pudding": "a bowl of chocolate pudding",
    "bagel": "a toasted bagel with cream cheese",
    "sushi_rolls": "sushi rolls arranged on a platter",
    "coconut": "a whole coconut with a straw",
    "grilled_vegetables": "a plate of grilled vegetables",
    "pot_pie": "a slice of pot pie on a plate",
    "fish_tacos": "fish tacos with fresh toppings",
    "hot_dog": "a hot dog served with condiments",
    "mango": "a ripe mango sliced on a plate",
    "barbecue": "a barbecue platter with meats",
    "pork_belly": "crispy pork belly on a plate",
    "fettuccine": "fettuccine Alfredo in a bowl",
    "bread_sticks": "a basket of breadsticks",
    "couscous": "a bowl of couscous with vegetables",
    "tostadas": "crispy tostadas with toppings",
    "sangria": "a glass of sangria with fruit",
    "chili_con_carne": "a bowl of chili con carne",
    "stuffed_peppers": "stuffed bell peppers on a plate",
    "pasta_salad": "a bowl of pasta salad with vegetables",
    "bento_box": "a bento box filled with assorted dishes",
    "caprese_salad": "a caprese salad with mozzarella and tomatoes",
    "quesadilla": "a cheesy quesadilla cut into wedges",
    "spinach_artichoke_dip": "a bowl of spinach artichoke dip with chips",
    "frozen_yogurt": "a cup of frozen yogurt with toppings",
    "ratatouille": "a serving of ratatouille in a dish",
    "chocolate_mousse": "a glass of chocolate mousse",
    "fruit_tart": "a fruit tart with a glossy finish",
    "mushroom_risotto": "a bowl of mushroom risotto",
    "stuffed_mushrooms": "stuffed mushrooms on a platter",
    "caponata": "a bowl of eggplant caponata",
    "pork_bun": "a bao bun filled with pork",
    "churros": "a plate of churros with chocolate sauce",
    "gyoza": "a plate of gyoza dumplings",
    "peanut_sauce": "a bowl of peanut sauce for dipping",
    "beef_stroganoff": "a plate of beef stroganoff with noodles",
    "salmon": "a grilled salmon fillet on a plate",
    "tuna_poke": "a bowl of tuna poke with avocado",
    "lentil_soup": "a bowl of lentil soup with herbs",
    "chicken_wings": "a platter of chicken wings with sauce",
    "cabbage_salad": "a fresh cabbage salad with dressing",
    "bangers_and_mash": "bangers and mash served on a plate",
    "potato_salad": "a bowl of potato salad with herbs",

    # Technology and Gadgets
    "smartphone": "a modern smartphone device with advanced features",
    "laptop_computer": "a portable laptop computer for various tasks",
    "desktop_setup": "a desktop computer setup with peripherals and monitor",
    "camera": "a digital or professional camera for photography and videography",
    "headphones": "audio headphones or earbuds for personal listening, including noise-cancelling options",
    "smartwatch": "a smartwatch worn on the wrist, featuring fitness tracking and notifications",
    "gaming_console": "a video game console for home entertainment and gaming",
    "tablet_device": "a versatile tablet computing device for media consumption and productivity",
    "drone": "a flying camera drone for aerial photography and videography",
    "robot": "a robot or robotic device used for automation and various tasks",
    "e_reader": "an electronic reader for digital books and documents",
    "fitness_tracker": "a wearable device for monitoring physical activity and health metrics",
    "smart_home_hub": "a central hub for connecting and controlling smart home devices",
    "VR_headset": "a virtual reality headset for immersive gaming and experiences",
    "Bluetooth_speaker": "a portable Bluetooth speaker for wireless audio playback",
    "action_camera": "an action camera designed for capturing high-action activities",
    "smart_tv": "a television with smart features for streaming and connectivity",
    "gaming_pc": "a high-performance gaming computer optimized for gaming",
    "3D_printer": "a printer for creating three-dimensional objects from digital designs",
    "wearable_camera": "a camera that can be worn for hands-free recording",
    "digital_voice_assistant": "a smart assistant device that responds to voice commands",
    "streaming_device": "a device for streaming media content to a TV or monitor",
    "smart_light_bulb": "a smart LED bulb for customizable and remote lighting",
    "home_security_camera": "a camera for monitoring and securing home premises",
    "projector": "a projector for displaying images and videos onto a screen",
    "robot_vacuum": "a robotic vacuum cleaner that automates home cleaning",
    "digital_photo_frame": "a digital frame for displaying a slideshow of photos",
    "wireless_router": "a wireless router for providing internet connectivity",
    "smart_thermostat": "a thermostat with smart technology for energy management",
    "smart_lock": "a smart lock for enhanced security and remote access to homes",
    "gaming_peripherals": "gaming accessories like mice, keyboards, and headsets for PCs",
    "portable_power_bank": "a portable charger for powering devices on the go",
    "graphics_tablet": "a tablet for digital art creation and graphic design",
    "mini_projector": "a compact projector for portable presentations",
    "smart_fridge": "a refrigerator equipped with smart features and connectivity",
    "electric_scooter": "an electric scooter for personal transportation and commuting",
    "solar_power_bank": "a solar-powered charger for charging devices using sunlight",
    "multi_device_charger": "a charger that can charge multiple devices at once",
    "smart_mirror": "a mirror with integrated technology for displaying information",
    "wireless_earbuds": "true wireless earbuds for audio without cables",
    "gaming_monitor": "a monitor designed for gaming with high refresh rates",
    "digital_thermometer": "a thermometer for precise temperature measurement",
    "security_system": "a comprehensive security system for homes or businesses",
    "USB_hub": "a hub for expanding USB connectivity options",
    "smart_speaker": "a speaker with built-in voice assistant capabilities",
    "home_automation_system": "a system for automating various home functions",
    "electric_bike": "an electric bicycle for efficient commuting and travel",
    "LED_strip_lights": "flexible LED strip lights for decorative and ambient lighting",
    "motion_sensor": "a sensor that detects motion for security and automation",
    "digital_scale": "a digital scale for accurate weight measurement",
    "smart_kitchen_appliance": "smart appliances designed for cooking and food preparation",
    "smartwatch_bands": "interchangeable bands for customizing smartwatches",
    "wireless_mouse": "a mouse that operates without cables for convenience",
    "camera_gimbal": "a stabilizing gimbal for smooth camera operation",
    "smart_plug": "a plug that allows remote control of devices plugged into it",
    "home_theater_system": "a system designed for creating a home theater experience",
    "car_dashcam": "a dashboard camera for recording driving footage",
    "cloud_storage_service": "a service for storing and accessing data online",
    "network_attached_storage": "a device for centralized storage accessible over a network",
    "air_quality_monitor": "a device for monitoring indoor air quality levels",
    "smart_washing_machine": "a washing machine with smart features for efficiency",
    "robotic_arm": "a programmable robotic arm for precise tasks",
    "smart_bluetooth_tracker": "a tracker for locating lost items using Bluetooth technology",
    "electric_kettle": "an electric kettle for quick boiling of water",
    "home_aquarium_monitor": "a device for monitoring conditions in an aquarium",
    "smart_garage_door_opener": "a smart opener for controlling garage doors remotely",

    # Sports and Activities
        "soccer_game": "a soccer match in progress",
    "basketball_game": "a basketball game being played",
    "tennis_match": "a tennis match on court",
    "swimming": "someone swimming in water",
    "yoga_pose": "someone in a yoga pose",
    "weightlifting": "someone lifting weights",
    "running": "someone running or jogging",
    "cycling": "someone riding a bicycle",
    "skiing": "someone skiing on snow",
    "skateboarding": "someone skateboarding",
    "volleyball_game": "a volleyball game being played",
    "baseball_game": "a baseball game in progress",
    "football_game": "a football game being played",
    "hiking": "someone hiking on a trail",
    "rock_climbing": "someone climbing a rock wall",
    "boxing": "two boxers in a ring",
    "martial_arts": "someone practicing martial arts",
    "gymnastics": "a gymnast performing a routine",
    "dancing": "someone dancing",
    "fishing": "someone fishing by a lake",
    "surfing": "someone surfing on a wave",
    "snowboarding": "someone snowboarding down a slope",
    "rollerblading": "someone rollerblading on a path",
    "horseback_riding": "someone riding a horse",
    "scooter_riding": "someone riding a scooter",
    "cricket_game": "a cricket match in progress",
    "ultimate_frisbee": "a game of ultimate frisbee",
    "table_tennis": "a table tennis match",
    "badminton": "a badminton game being played",
    "lacrosse": "a lacrosse game in action",
    "field_hockey": "a field hockey match",
    "handball": "a handball game being played",
    "cheerleading": "cheerleaders performing a routine",
    "gymnastics_routine": "a gymnast performing on the balance beam",
    "skating": "someone ice skating on a rink",
    "petanque": "a game of petanque being played",
    "curling": "curlers sliding stones on ice",
    "paddleboarding": "someone paddleboarding on water",
    "kite_surfing": "someone kite surfing on a beach",
    "trampolining": "someone jumping on a trampoline",
    "parkour": "someone practicing parkour",
    "darts": "someone throwing darts at a board",
    "snorkeling": "someone snorkeling in the ocean",
    "scuba_diving": "someone scuba diving underwater",
    "sailing": "someone sailing on a boat",
    "tug_of_war": "a tug-of-war competition",
    "futsal": "a futsal game being played",
    "swimming_race": "a competitive swimming race",
    "crossfit": "someone participating in a CrossFit workout",
    "zumba": "a group doing Zumba dance fitness",
    "tai_chi": "someone practicing tai chi",
    "motorsport": "a motorsport race in progress",
    "aerial_silk": "someone performing on aerial silks",
    "bouldering": "someone bouldering on a rock",
    "bodyboarding": "someone bodyboarding on a wave",
    "synchronized_swimming": "a synchronized swimming routine",
    "kickboxing": "someone practicing kickboxing",
    "cheerleading_routine": "a cheerleading team performing a routine",
    "lawn_bowls": "a game of lawn bowls being played",
    "pickleball": "a game of pickleball in action",
    "powerlifting": "someone competing in powerlifting",
    "quad_riding": "someone riding a quad bike",
    "water_polo": "a water polo match in progress",
    "slacklining": "someone balancing on a slackline",
    "equestrian": "someone participating in equestrian events",
    "fencing": "two fencers engaged in a match",
    "indoor_climbing": "someone climbing indoors on a climbing wall",
    "strength_training": "someone engaged in strength training exercises",
    "kettlebell_training": "someone using kettlebells in a workout",
    "speed_skating": "speed skaters racing on ice",
    "orienting": "someone participating in orienteering",
    "robotics_competition": "teams competing in a robotics challenge",
    "virtual_reality_gaming": "someone playing a virtual reality game",

    # Art and Creativity
        "painting": "a painted artwork on canvas",
    "sculpture": "a sculptural artwork",
    "street_art": "street art or graffiti",
    "digital_art": "digital artwork or illustration",
    "sketch": "a hand-drawn sketch",
    "pottery": "handmade ceramic pottery",
    "textile_art": "artistic textile or fabric work",
    "installation_art": "an art installation",
    "performance_art": "performance art being performed",
    "glass_art": "artistic glasswork",
    "photography": "a photographic artwork",
    "mosaic": "a mosaic artwork made from tiles or glass pieces",
    "collage": "a collage of various materials and images",
    "printmaking": "artwork created through printmaking techniques",
    "calligraphy": "decorative handwriting or handwritten lettering",
    "illustration": "an illustration or drawing, often for books or magazines",
    "ceramics": "functional or decorative ceramic objects",
    "graffiti": "artistic spray paint designs on walls",
    "digital_collage": "a collage made with digital images",
    "mixed_media": "art created using a mix of different materials and methods",
    "body_art": "body art including tattoos or body paint",
    "land_art": "art created in nature using natural materials",
    "installation": "a temporary or permanent installation artwork",
    "fresco": "a mural painted on wet plaster",
    "light_art": "artworks created using light as the medium",
    "conceptual_art": "art that emphasizes ideas over traditional aesthetics",
    "abstract_art": "art that does not attempt to represent external reality",
    "art_brut": "outsider art, often created by self-taught artists",
    "street_performance": "performance art that occurs in public spaces",
    "performance_installation": "a blend of performance art and installation art",
    "text_art": "art that incorporates text as a central element",
    "art_photography": "photography that has artistic intent",
    "artistic_techniques": "various techniques used in creating art",
    "neo_classical_art": "art inspired by classical antiquity",
    "art_movement": "a specific movement in art history",
    "video_art": "artworks created using video technology",
    "3D_art": "three-dimensional artwork created using various materials",
    "embroidery": "artistic needlework using threads and fabrics",
    "fiber_art": "art created with fibers and textiles",
    "environmental_art": "art that addresses environmental issues",
    "public_art": "artwork displayed in public spaces for community engagement",
    "community_art": "art created in collaboration with community members",
    "art_education": "the practice of teaching art",
    "art_therapy": "the use of art in therapy to improve mental health",
    "illustrative_design": "design that incorporates illustrations",
    "art_journalism": "journalism that covers the art world",
    "art_conservation": "the preservation and restoration of artworks",
    "street_photography": "photography that captures candid moments in urban settings",
    "art_installation": "an artwork created to transform a specific space",
    "visual_art": "art that is primarily visual in nature",
    "interactive_art": "art that requires the participation of the viewer",
    "performance_poetry": "poetry that is performed live as an art form",
    "conceptual_installation": "an installation focused on conveying an idea or concept",
    "artistic_expression": "the way in which artists convey emotions or ideas through their work",
    "cultural_art": "art that reflects cultural identity or heritage",
    "digital_installation": "an installation that incorporates digital media and technology",
    "sound_art": "art that uses sound as a primary medium",
    "art_sculpture": "a sculpture that explores artistic themes or ideas",
    "community_mural": "a mural created collaboratively by a community",
    "artistic_collaboration": "joint efforts by artists to create artwork",
    "art_fair": "an event where artists and galleries display their work for sale",
    "artist_residency": "a program that provides artists with time and space to create new work",
    "art_lecture": "a talk or presentation about art and its various forms",

    # Fashion and Style
        "casual_outfit": "casual everyday outfit",
    "formal_wear": "formal or business attire",
    "streetwear": "urban streetwear fashion",
    "athletic_wear": "athletic or sports clothing",
    "activewear_set": "matching athletic clothing sets",
    "evening_gown": "formal evening gown",
    "cocktail_dress": "semi-formal dress for evening events",
    "suits": "business or formal suits",
    "accessories": "fashion accessories",
    "jewelry": "jewelry and precious items",
    "shoes": "fashionable footwear",
    "sneakers": "casual athletic shoes",
    "boots": "durable and stylish footwear",
    "handbags": "designer or fashion handbags",
    "tote_bags": "large bags for carrying items, often with an open top",
    "crossbody_bags": "bags worn across the body with a long strap",
    "clutches": "small, handheld bags for formal occasions",
    "summer_dress": "light and breezy summer dress",
    "maxi_dress": "long, flowy dress suitable for casual or formal occasions",
    "winter_coat": "warm and stylish winter outerwear",
    "bomber_jacket": "casual, fitted jacket with a zip",
    "puffer_jacket": "insulated outerwear for cold weather",
    "denim_jacket": "classic denim outerwear",
    "graphic_tshirts": "t-shirts with artistic designs",
    "sweaters": "knit garments for warmth",
    "graphic_sweaters": "sweaters featuring bold designs or text",
    "cardigans": "open front knitted sweaters",
    "flannel_shirt": "soft, checked shirt typically made of flannel fabric",
    "trench_coat": "long, double-breasted coat with a belt",
    "peacoat": "short, double-breasted wool coat",
    "trousers": "formal or casual pants",
    "chinos": "casual trousers made of cotton",
    "shorts": "casual or sporty short pants",
    "leggings": "tight-fitting stretchable pants",
    "culottes": "wide-legged cropped pants",
    "overalls": "one-piece garment for work or casual wear",
    "rompers": "one-piece outfits with shorts, suitable for casual wear",
    "playsuits": "one-piece garments with shorts, suitable for casual wear",
    "pajamas": "comfortable sleepwear",
    "lingerie": "intimate apparel for women",
    "maternity_wear": "clothing designed for expectant mothers",
    "distressed_denim": "jeans with intentional rips or wear",
    "sweatpants": "comfortable pants designed for athletic use",
    "boots": "durable and stylish footwear",
    "ballet_flats": "flat, slip-on shoes with a thin heel",
    "oxfords": "classic lace-up shoes, often made of leather",
    "mules": "slip-on shoes with no back or heel strap",
    "clogs": "backless shoes, often made of wood or heavy material",
    "wedge_heels": "shoes with a wedge-shaped heel for added height",
    "platform_shoes": "shoes with thick soles for height and comfort",
    "socks": "fashionable and functional socks",
    "sunglasses": "stylish eyewear for sun protection",
    "hats": "fashionable headwear",
    "beanies": "knitted caps for warmth and style",
    "bucket_hat": "casual, soft hat with a downward-sloping brim",
    "fedoras": "stylish wide-brimmed hats",
    "scarves": "accessories for warmth and style",
    "belts": "stylish and functional belts",
    "suspenders": "straps worn to hold up trousers",
    "cufflinks": "decorative fasteners for shirt cuffs",
    "brooches": "decorative pins worn on clothing",
    "pins_and_badges": "small decorative items attached to clothing",
    "headbands": "hair accessories worn across the forehead",
    "tattoos": "body art that can be a fashion statement",
    "eco_fashion": "sustainable and environmentally-friendly clothing",
    "vintage_fashion": "clothing styles from past eras",
    "bohemian_style": "eclectic and artistic fashion",
    "minimalist_style": "simple and clean clothing designs",
    "punk_fashion": "edgy and rebellious clothing styles",
    "luxury_fashion": "high-end designer clothing",
    "couture": "high fashion custom-made garments",
    "ethnic_wear": "traditional clothing from various cultures",
    "street_style": "trendy and urban casual wear",
    "layered_outfits": "multiple layers of clothing for style and warmth",
    "faux_fur": "synthetic fur used for outerwear and accessories",
    "athleisure": "casual clothing designed for both exercise and everyday wear",
    "kimono": "traditional Japanese robe, often with elaborate designs",

    # Transportation
        "car": "a car on the road",
    "motorcycle": "a motorcycle vehicle",
    "bicycle": "a bicycle",
    "bus": "a public transport bus",
    "train": "a passenger train",
    "airplane": "an airplane in flight",
    "boat": "a boat on water",
    "helicopter": "a helicopter flying",
    "subway": "a subway or metro train",
    "electric_scooter": "an electric scooter",
    "truck": "a delivery truck",
    "van": "a cargo van",
    "pickup_truck": "a pickup truck",
    "segway": "a segway personal transporter",
    "hoverboard": "a hoverboard",
    "trolleybus": "a trolleybus",
    "trailer": "a trailer being towed",
    "golf_cart": "a golf cart",
    "ambulance": "an ambulance vehicle",
    "fire_truck": "a fire truck",
    "taxi": "a taxi cab",
    "limo": "a limousine",
    "double_decker_bus": "a double-decker bus",
    "monorail": "a monorail train",
    "funicular": "a funicular railway",
    "ferry": "a ferry boat",
    "cargo_ship": "a cargo ship",
    "yacht": "a yacht on the water",
    "submarine": "a submarine underwater",
    "hot_air_balloon": "a hot air balloon in the sky",
    "blimp": "a blimp or airship",
    "kite": "a kite flying in the air",
    "skateboard": "a skateboard on a path",
    "rollerblade": "a person rollerblading",
    "electric_bicycle": "an electric bicycle",
    "tricycle": "a tricycle",
    "dirt_bike": "a dirt bike on a trail",
    "scooter": "a kick scooter",
    "bicycle_taxi": "a bicycle taxi",
    "rickshaw": "a rickshaw vehicle",
    "sled": "a sled on snow",
    "snowmobile": "a snowmobile on snow",
    "monowheel": "a monowheel personal vehicle",
    "electric_hoverboard": "an electric hoverboard",
    "pedal_boat": "a pedal boat on a lake",
    "skiff": "a small skiff on water",
    "catamaran": "a catamaran sailing",
    "jet_ski": "a jet ski on water",
    "paddleboard": "a paddleboarder on water",

    # Events and Occasions
        "concert": "a live music concert",
    "festival": "a festival celebration",
    "birthday_party": "a birthday party celebration",
    "wedding_ceremony": "a wedding ceremony",
    "conference": "a business conference",
    "parade": "a street parade",
    "sports_event": "a sports event with crowd",
    "graduation_ceremony": "a graduation ceremony",
    "exhibition": "an art or museum exhibition",
    "fashion_show": "a fashion show runway",
    "family_reunion": "a gathering of family members",
    "workshop": "an educational workshop or seminar",
    "seminar": "an academic seminar",
    "trade_show": "a business trade show",
    "community_meeting": "a meeting for community discussion",
    "charity_event": "a fundraising charity event",
    "picnic": "an outdoor picnic gathering",
    "open_mic_night": "a night of open microphone performances",
    "theater_play": "a live theater performance",
    "comedy_show": "a live comedy performance",
    "film_festival": "a festival showcasing films",
    "book_launch": "a launch event for a new book",
    "art_gallery_opening": "an opening event for an art gallery",
    "cultural_festival": "a festival celebrating cultural heritage",
    "food_festival": "a festival dedicated to food and culinary arts",
    "new_years_eve_party": "a celebration for New Year's Eve",
    "block_party": "a neighborhood block party",
    "baby_shower": "a celebration for an expecting mother",
    "retirement_party": "a party honoring someone's retirement",
    "holiday_party": "a party celebrating a holiday",
    "funeral_service": "a service to honor the deceased",
    "corporate_retreat": "a company retreat for employees",
    "music_festival": "a large festival featuring multiple musical acts",
    "street_fair": "a fair held on the streets with vendors and entertainment",
    "high_school_reunion": "a reunion for former high school classmates",
    "spiritual_gathering": "a gathering for spiritual practices",
    "hiking_trip": "a group hiking excursion",
    "cooking_class": "a class for teaching cooking skills",
    "networking_event": "an event for professional networking",
    "science_fair": "a fair showcasing science projects and innovations",
    "dance_competition": "a competition showcasing dance performances",
    "carnival": "a festive event with rides and games",
    "mardi_gras": "a celebration with parades and costumes",
    "wrestling_event": "a live professional wrestling event",
    "open_house": "an event for showing a property or facility",
    "scavenger_hunt": "a game involving searching for items or clues",
    "car_show": "an exhibition of cars and automotive culture",
    "poker_tournament": "a competitive poker event",
    "art_fair": "a fair showcasing various art forms",
    "pet_show": "a showcase event for pets",
    "haunted_house": "a spooky attraction for Halloween",
    "zombie_walk": "an event where participants dress as zombies",
    "yoga_retreat": "a retreat focused on yoga practice",
    "surf_competition": "a competition showcasing surfing skills",
    "fashion_fair": "a fair focusing on fashion and clothing",
    "adventure_race": "a race involving multiple outdoor challenges",
    "music_workshop": "a workshop for music education",
    "garden_show": "an exhibition showcasing gardening and plants",

    # Weather and Atmospheric
        "stormy_sky": "a stormy sky with clouds",
    "rainbow": "a rainbow in the sky",
    "lightning": "lightning in the sky",
    "snow_scene": "a snowy winter scene",
    "foggy_scene": "a foggy atmospheric scene",
    "rain": "rain falling from clouds",
    "cloudy_sky": "a cloudy sky",
    "clear_sky": "a clear blue sky",
    "northern_lights": "aurora borealis in the sky",
    "misty_morning": "a misty morning scene",
    "thunderstorm": "a thunderstorm with dark clouds",
    "hurricane": "a hurricane over the ocean",
    "blizzard": "a blizzard with heavy snow",
    "sunny_day": "a bright sunny day",
    "overcast": "an overcast sky",
    "drizzle": "light rain or drizzle",
    "hail": "hailstones falling from clouds",
    "tornado": "a tornado touching down",
    "frost": "frost covering the ground",
    "heatwave": "a dry and hot landscape",
    "dusk": "a dusky sky at twilight",
    "dawn": "the first light of dawn",
    "severe_weather": "severe weather conditions",
    "smoky_sky": "a smoky sky from wildfires",
    "dust_storm": "a dust storm in the desert",
    "sandstorm": "a sandstorm sweeping across the landscape",
    "tropical_storm": "a tropical storm with heavy rain",
    "clear_night": "a clear night sky full of stars",
    "starry_sky": "a sky filled with stars",
    "moonlit_night": "a night scene illuminated by the moon",
    "sunset": "a beautiful sunset over the horizon",
    "sunrise": "a sunrise breaking over the landscape",
    "flood": "floodwaters covering an area",
    "icy_scene": "an icy landscape with frozen lakes",
    "tropical_rain": "heavy rain in a tropical setting",
    "mist": "a light mist hanging in the air",
    "cloud_burst": "a sudden heavy rainfall from clouds",
    "gale": "strong winds blowing through trees",
    "whirlwind": "a whirlwind moving across the ground",
    "polar_night": "a night scene in polar regions",
    "arctic_scene": "an arctic landscape with snow and ice",
    "tundra": "a tundra landscape with low vegetation",
    "weather_vane": "a weather vane indicating wind direction",
    "raindrop": "raindrops falling on a surface",
    "dew": "dew drops on grass in the morning",
    "funnel_cloud": "a funnel cloud forming",
    "serene_scene": "a peaceful and serene weather scene",

    # Interior Design
        "living_room": "a decorated living room interior",
    "kitchen": "a modern kitchen interior",
    "bedroom": "a bedroom interior design",
    "bathroom": "a bathroom interior",
    "office_space": "an office workspace interior",
    "dining_room": "a dining room setup",
    "home_library": "a home library with books",
    "home_gym": "a home gym setup",
    "children_room": "a children's bedroom",
    "minimalist_interior": "a minimalist interior design",
    "industrial_style": "an industrial style interior",
    "cozy_nook": "a cozy reading nook",
    "open_floor_plan": "an open floor plan design",
    "luxury_bathroom": "a luxury bathroom with a spa feel",
    "modern_apartment": "a modern apartment interior",
    "traditional_living_room": "a traditional living room setup",
    "rustic_kitchen": "a rustic kitchen interior",
    "scandinavian_design": "a Scandinavian design living area",
    "bohemian_style": "a bohemian style interior",
    "home_office": "a stylish home office setup",
    "game_room": "a game room with entertainment options",
    "patio": "a decorated outdoor patio",
    "sunroom": "a bright and airy sunroom",
    "laundry_room": "a functional laundry room",
    "entryway": "an inviting entryway interior",
    "craft_room": "a craft room with supplies",
    "guest_room": "a cozy guest room setup",
    "zen_space": "a calming zen-inspired space",
    "high_tech_home": "a high-tech home interior",
    "art_studio": "an art studio with creative space",
    "media_room": "a media room for entertainment",
    "contemporary_bathroom": "a contemporary bathroom design",
    "vintage_style": "a vintage style interior",
    "smart_kitchen": "a smart kitchen with modern appliances",
    "family_room": "a family room designed for gatherings",
    "workspace": "a functional workspace with modern decor",
    "outdoor_kitchen": "an outdoor kitchen for entertaining",
    "nursery": "a nursery designed for infants",
    "home_theater": "a home theater setup",
    "loft_style": "a loft-style apartment interior",
    "southwestern_interior": "a southwestern style interior",
    "mid_century_modern": "a mid-century modern living space",
    "eclectic_style": "an eclectic interior with diverse elements",
    "cottage_style": "a cozy cottage style interior",
    "elegant_dining": "an elegant dining room setup",
    "modern_bedroom": "a sleek modern bedroom design",
    "tranquil_bathroom": "a tranquil bathroom oasis",
    "romantic_bedroom": "a romantic bedroom atmosphere",
    "artistic_space": "an artistic space for creativity",

    # Abstract and Experimental
    "abstract_pattern": "an abstract pattern design",
    "geometric_abstract": "geometric abstract artwork",
    "color_field": "abstract color field",
    "motion_blur": "artistic motion blur",
    "double_exposure": "double exposure photograph",
    "light_painting": "light painting photography",
    "kaleidoscope": "kaleidoscopic pattern",
    "fractal": "fractal pattern artwork",
    "glitch_art": "digital glitch artwork",
    "minimalist_abstract": "minimalist abstract design",
    "surrealism": "surreal abstract imagery",
    "abstract_expressionism": "abstract expressionist painting",
    "dynamic_lines": "dynamic line art",
    "organic_shapes": "organic shape abstraction",
    "textured_surface": "textured abstract surface",
    "color_wave": "color wave abstract design",
    "drip_art": "drip painting technique",
    "3d_render": "three-dimensional abstract render",
    "pixel_art": "pixelated abstract art",
    "aerial_view": "aerial abstract composition",
    "digital_collage": "digital collage artwork",
    "abstract_landscape": "abstract landscape interpretation",
    "neon_lights": "neon light abstract art",
    "paper_cut": "paper cut abstract design",
    "conceptual_art": "conceptual abstract expression",
    "optical_illusion": "optical illusion artwork",
    "color_splash": "color splash abstract art",
    "abstract_portrait": "abstract portrait representation",
    "fractured_geometry": "fractured geometric patterns",
    "symmetrical_design": "symmetrical abstract design",
    "abstract_silhouette": "abstract silhouette art",
    "time_lapse": "time-lapse abstract imagery",
    "layered_textures": "layered texture artwork",
    "animated_visuals": "animated abstract visuals",
    "cosmic_art": "cosmic and galactic abstractions",
    "abstract_typography": "abstract typography design",
    "bokeh_effect": "bokeh effect photography",
    "chromatic_aberration": "chromatic aberration effect",
    "pattern_repetition": "pattern repetition artwork",
    "monochrome_art": "monochrome abstract design",
    "vintage_effect": "vintage abstract art",
    "hyperrealism": "hyperreal abstract representation",
    "subtle_gradients": "subtle gradient abstract art",
    "fluid_art": "fluid art technique",
    "paper_mache": "paper mache abstract sculpture",
    "doodle_art": "doodle abstract design",
    "line_art": "line art abstraction",
    "visual_poetry": "visual poetry in abstract form",
    "spatial_art": "spatial abstract compositions",
    "retro_vibes": "retro-inspired abstract design",
    "collage_art": "mixed media collage abstraction",
    "futuristic_design": "futuristic abstract aesthetics",
    "abstract_sculpture": "abstract three-dimensional sculpture",
    "sound_wave": "sound wave visual representation",
    "cinematic_abstract": "cinematic abstract visuals",

    # Medical and Scientific
        "xray_image": "an x-ray medical image",
    "microscope_view": "microscopic photograph",
    "medical_scan": "medical scanning image",
    "laboratory": "scientific laboratory setup",
    "surgery_room": "operating room in hospital",
    "dental_photo": "dental photography",
    "medical_equipment": "medical equipment and devices",
    "scientific_diagram": "scientific diagram or chart",
    "molecule_model": "molecular structure model",
    "brain_scan": "brain scanning image",
    "blood_test": "blood sample analysis",
    "ultrasound_image": "ultrasound imaging",
    "ct_scan": "computed tomography scan",
    "pet_scan": "positron emission tomography scan",
    "clinical_trial": "clinical trial documentation",
    "vaccine_development": "vaccine research process",
    "genetic_sequence": "genetic sequencing data",
    "anatomy_chart": "human anatomy chart",
    "pharmaceuticals": "pharmaceutical products",
    "diagnostic_tools": "diagnostic medical tools",
    "medical_research": "medical research laboratory",
    "healthcare_professionals": "healthcare professionals at work",
    "surgical_instruments": "surgical instruments set",
    "neuroscience_research": "neuroscience laboratory setup",
    "tissue_sample": "tissue sample preparation",
    "biomedical_engineering": "biomedical engineering projects",
    "cardiogram": "electrocardiogram (ECG) image",
    "pathology_slide": "pathology microscope slide",
    "radiology": "radiology imaging techniques",
    "endoscopy": "endoscopic procedure",
    "healthcare_technology": "healthcare technology innovation",
    "clinical_observations": "clinical observations report",
    "public_health": "public health initiatives",
    "immunology_research": "immunology laboratory",
    "epidemiology": "epidemiological study",
    "biostatistics": "biostatistical analysis",
    "forensic_science": "forensic science investigation",
    "microbiology": "microbiology laboratory",
    "biochemistry": "biochemistry research",
    "environmental_science": "environmental science field study",
    "toxicology": "toxicology testing procedures",
    "pharmacology": "pharmacology research studies",
    "physiotherapy": "physiotherapy session",
    "medical_ethics": "medical ethics discussion",
    "nutritional_science": "nutritional science research",
    "pediatrics": "pediatric healthcare",
    "geriatrics": "geriatric healthcare",
    "obstetrics": "obstetrics and gynecology",
    "orthopedics": "orthopedic treatment and surgery",
    "psychology_lab": "psychology research laboratory",
    "oncology": "oncology research and treatment",
}