myDict = {
    'i1.png':'What is the woman doing?',
    'i2.png':'What is the utensil present?',
    'i3.png':'How many flower pots are there that have blue flowers?',
    'i4.png':'What color is the bridge if someone painted it green?',
    'i5.png':'What is the number on the helmet?',
    'i6.png':'How many seeds should I expect from this apple?',
    'i7.png':'Where does this come from and which country is next to it?',
    'i8.png':'How many people are on the balcony that are male?',
    'i9.png':'How many blue eyes does the frog have?',
    'i10.png':'What are the colors here?',
    'i11.png':'What will happen if I were to drop it from my roof?',
    'i12.png':'What is the color of the water bottle?',
    'i13.png':'What is the color of the hat the man is wearing?',
    'i14.png':'What is this and what can I do with it?',
    'i15.png':'Where are we right now?',
    'i16.png':'How many orange stars are there if we put an orange star on the bear?',
    'i17.png':'How many pillows are there that are beige?',
    'i18.png':'How long will it take for all of the icecubes to melt?',
    'i19.png':'What are the colors in the image and what will the color be if I combined all of them?',
    'i20.png':'How many bananas are there if I took one away?',
}