CAPTION_PROMPTS = [
    "Describe this image.",
    "Write a caption for this image.",
    "What does this image show?",
    "Generate a caption describing this image.",
    "Provide a description of this image.",
    "What's depicted in this image?",
    "Write a description for this image.",
    "Generate text describing this image.",
    "Create a caption for this image.",
    "What can you see in this image?",
    "Describe what you observe in this image.",
    "Write text explaining this image.",
    "Generate a description of this image.",
    "What is shown in this image?",
    "Provide a caption for this image.",
    "Explain what this image depicts.",
    "Write what you see in this image.",
    "Describe the contents of this image.",
    "Generate text about this image.",
    "What appears in this image?"
]
